= Upgrade a RHOSP 17.1 to RHOSO 18 using the adoption mechanism through an example
:navtitle: Home

== Introduction

This is the course for IT professionals who are already experienced with OpenStack and they want to learn how to upgrade their environment to RHOSO 18.0 using the adoption mechanism. It requires no previous knowledge of Red Hat OpenShift, Kubernetes, and containers, but it requires familiarity with managing application workloads running as virtual machines (VM) on OpenStack and managing associated resources such as storage volumes and tenant or provider networks.

This course helps both experienced OpenStack Administrators and OpenStack Operators who are growing into OpenStack Administrators understand the Red Hat OpenStack Services on OpenShift products and how managing it may be different than managing other incarnations of the Red Hat OpenStack Platform.

== Course Objective

As a result of taking this course, Administrators of Red Hat OpenStack clusters will be able to upgrade a RHOSP 17.1 to RHOSO 18 using the adoption mechanism.

== Audience

Platform Engineers, Cloud Administrators, and System Administrators interested in deploying and managing Red Hat OpenStack clusters.

== Pre-requisites

* Basic administration of RHEL: https://www.redhat.com/en/services/training/rh124-red-hat-system-administration-i[RH124]

* Basic experience with Red Hat OpenStack Platform 17.1

* Basic operation of OpenStack Services on OpenShift: https://redhatquickcourses.github.io/rhoso-intro/[OSP-Operations-I-1] and OSP-Operations-I-2, or the equivalent courses from previous releases of Red Hat OpenStack, such as https://www.redhat.com/en/services/training/cl110-red-hat-openstack-administration-i[CL110] and https://www.redhat.com/en/services/training/cl210-red-hat-openstack-administration-ii[CL210].

* Basic data center storage concepts: storage protocols, NAS, and SAN.

* Data center networking concepts: ISO model, VLANs, firewalls, and Internet protocols, including but not limited to ICMP, IP, and HTTP.

* Basic object storage concepts, such as experience with AWS S3, are useful but not required.

* Ceph administration skills are useful but not required.

