:_mod-docs-content-type: PROCEDURE
[id="adopting-the-networking-service_{context}"]

= Adopting the {networking_service}

[role="_abstract"]
To adopt the {networking_first_ref}, you patch an existing `OpenStackControlPlane` custom resource (CR) that has the {networking_service} disabled. The patch starts the service with the
configuration parameters that are provided by the {rhos_prev_long} ({OpenStackShort}) environment.

The {networking_service} adoption is complete if you see the following results:

* The `NeutronAPI` service is running.
* The {identity_service_first_ref} endpoints are updated, and the same back end of the source cloud is available.


.Prerequisites

* Ensure that Single Node OpenShift or OpenShift Local is running in the {rhocp_long} cluster.
* Adopt the {identity_service}. For more information, see xref:adopting-the-identity-service_adopt-control-plane[Adopting the {identity_service}].
* Migrate your OVN databases to `ovsdb-server` instances that run in the {rhocp_long} cluster. For more information, see xref:migrating-ovn-data_migrating-databases[Migrating OVN data].


.Procedure

* Patch the `OpenStackControlPlane` CR to deploy the {networking_service}:
+
[source,bash,role=execute]
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  neutron:
    enabled: true
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 192.168.52.89
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      databaseAccount: neutron
      secret: osp-secret
      networkAttachments:
      - internalapi
'
----

.Verification

* Inspect the resulting {networking_service} pods:
+
[source,bash,role=execute]
----
oc get pods -l service=neutron
----

* Ensure that the `Neutron API` service is registered in the {identity_service}:
+
[source,bash,role=execute]
----
openstack service list | grep network
----
+
[source,bash,role=execute]
----
openstack endpoint list | grep network
----
+
Sample output:
+
----
| a866aef3d9354bf6b37110692e1e5aee | regionOne | neutron      | network      | True    | internal  | http://neutron-internal.openstack.svc:9696             |
| b0f4743dc3e24fd8acf7b406d6f92ea5 | regionOne | neutron      | network      | True    | public    | http://neutron-public-openstack.apps.ocp4.example.com  |
----

* Create sample resources so that you can test whether the user can create networks, subnets, ports, or routers:
+
[source,bash,role=execute]
----
openstack network create net
openstack subnet create --network net --subnet-range 10.0.0.0/24 subnet
openstack router create router
----
