:_mod-docs-content-type: PROCEDURE
[id="adopting-networker-services-to-the-data-plane_{context}"]

= Adopting Networker services to the {rhos_acro} data plane

[role="_abstract"]
Adopt the Networker services in your existing {rhos_prev_long} deployment to the {rhos_long} data plane. In this environment, the `Networker` services run on dedicated `Networker` nodes. You decide which services you want to run on the Networker nodes, and create a separate `OpenStackDataPlaneNodeSet` custom resource (CR) for the Networker nodes. You might also decide to implement the following options if they apply to your environment:

* If you want to continue running OVN gateway services on Networker nodes, keep `ovn` service in the list to deploy.

Adopt each Networker node in your existing {rhos_prev_long} deployment to the {rhos_long} when your node is set as an OVN chassis gateway. Any node with
parameter set to `enable-chassis-as-gw` is considered OVN gateway chassis. In this case, such nodes will become edpm networker nodes after adoption.

. Check for the nodes where `OVN Controller Gateway agent` agents are running. The list of agents varies depending on the services you enabled:
+
[source,bash,role=execute]
----
oc exec openstackclient -- openstack network agent list
+--------------------------------------+------------------------------+-------------------------------------+-------------------+-------+-------+----------------------------+
| ID                                   | Agent Type                   | Host                                | Availability Zone | Alive | State | Binary                     |
+--------------------------------------+------------------------------+-------------------------------------+-------------------+-------+-------+----------------------------+
| ad88316a-0f35-4a6e-87c8-db6a792e566f | OVN Controller agent         | overcloud-controller-1.localdomain  |                   | XXX   | UP    | ovn-controller             |
| b182ecee-95ff-4c10-8698-23936d97b3d7 | OVN Controller agent         | overcloud-controller-2.localdomain  |                   | XXX   | UP    | ovn-controller             |
| 248abd88-f08e-441f-8560-aa5520757d68 | OVN Controller Gateway agent | overcloud-networker.localdomain     |                   | XXX   | UP    | ovn-controller             |
| bd7fbc34-aca7-5f0b-8fba-abe4ba279c8a | OVN Metadata agent           | overcloud-novacompute-0.localdomain |                   | :-)   | UP    | neutron-ovn-metadata-agent |
| 238beac8-d417-4098-b712-5350823f08d5 | OVN Controller agent         | overcloud-novacompute-0.localdomain |                   | :-)   | UP    | ovn-controller             |
| 3fb27b31-9381-42be-89ed-b3a6f6f6a328 | OVN Controller agent         | overcloud-controller-0.localdomain  |                   | XXX   | UP    | ovn-controller             |
| eb4f018e-91ac-5f05-b0c2-a7c16935fe78 | OVN Metadata agent           | overcloud-novacompute-1.localdomain |                   | :-)   | UP    | neutron-ovn-metadata-agent |
| ef0ba743-2339-42b4-9535-21f70b8e5d5a | OVN Controller agent         | overcloud-novacompute-1.localdomain |                   | :-)   | UP    | ovn-controller             |
+--------------------------------------+------------------------------+-------------------------------------+-------------------+-------+-------+----------------------------+
----

.Prerequisites

* Define the shell variable. Based on above agent list output,
overcloud-networker.localdomain is our target
host.
+
[source,bash,role=execute]
----
declare -A networkers
networkers+=(
  ["overcloud-networker"]="172.25.249.250"
)
----

.Procedure

. Deploy the `OpenStackDataPlaneNodeSet` CR for your nodes:
+
[NOTE]
You can reuse most of the `nodeTemplate` section from the `OpenStackDataPlaneNodeSet` CR that is designated for your Compute nodes. You can omit some of the variables because of the limited set of services that are running on the Networker nodes.
+
[source,bash,role=execute]
----
oc apply -f osp-ng-dataplane-node-set-deploy-adoption-networker.yaml
----
+

. Run the `pre-adoption-validation` service for Networker nodes:

.. Create a `OpenStackDataPlaneDeployment` CR that runs only the validation:
+
[source,bash,role=execute]
----
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-pre-adoption-networker
spec:
  nodeSets:
  - openstack-networker
  servicesOverride:
  - pre-adoption-validation
EOF
----

.. When the validation is finished, confirm that the status of the Ansible EE pods is `Completed`:
+
[source,bash,role=execute]
----
watch oc get pod -l app=openstackansibleee
----
+
[source,bash,role=execute]
----
oc logs -l app=openstackansibleee -f --max-log-requests 20
----

.. Wait for the deployment to reach the `Ready` status:
+
[source,bash,role=execute]
----
oc wait --for condition=Ready openstackdataplanedeployment/openstack-pre-adoption-networker --timeout=10m
----

. Deploy the `OpenStackDataPlaneDeployment` CR for Networker nodes:
+
[source,bash,role=execute]
----
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-networker
spec:
  nodeSets:
  - openstack-networker
EOF
----

.. Wait for the deployment to reach the `Ready` status:
+
[source,bash,role=execute]
----
oc wait --for condition=Ready openstackdataplanedeployment/openstack-networker --timeout=10m
----

+

. Clean up any {networking_first_ref} agents that are no longer running.
+
[NOTE]
In some cases, agents from the old data plane that are replaced or retired remain in {rhos_acro}. The function these agents provided might be provided by a new agent that is running in {rhos_acro}, or the function might be replaced by other components. For example, DHCP agents might no longer be needed, since OVN DHCP in {rhos_acro} can provide this function.

.. List the agents:
+
[source,bash,role=execute]
----
oc exec openstackclient -- openstack network agent list
----
+
Sample output:
+
----
+--------------------------------------+------------------------------+-------------------------------------+-------------------+-------+-------+----------------------------+
| ID                                   | Agent Type                   | Host                                | Availability Zone | Alive | State | Binary                     |
+--------------------------------------+------------------------------+-------------------------------------+-------------------+-------+-------+----------------------------+
| ad88316a-0f35-4a6e-87c8-db6a792e566f | OVN Controller agent         | overcloud-controller-1.localdomain  |                   | XXX   | UP    | ovn-controller             |
| 248abd88-f08e-441f-8560-aa5520757d68 | OVN Controller Gateway agent | overcloud-networker.localdomain     |                   | :-)   | UP    | ovn-controller             |
| ef0ba743-2339-42b4-9535-21f70b8e5d5a | OVN Controller agent         | overcloud-novacompute-1.localdomain |                   | :-)   | UP    | ovn-controller             |
| eb4f018e-91ac-5f05-b0c2-a7c16935fe78 | OVN Metadata agent           | overcloud-novacompute-1.localdomain |                   | :-)   | UP    | neutron-ovn-metadata-agent |
| 3fb27b31-9381-42be-89ed-b3a6f6f6a328 | OVN Controller agent         | overcloud-controller-0.localdomain  |                   | XXX   | UP    | ovn-controller             |
| b182ecee-95ff-4c10-8698-23936d97b3d7 | OVN Controller agent         | overcloud-controller-2.localdomain  |                   | XXX   | UP    | ovn-controller             |
| 238beac8-d417-4098-b712-5350823f08d5 | OVN Controller agent         | overcloud-novacompute-0.localdomain |                   | :-)   | UP    | ovn-controller             |
| bd7fbc34-aca7-5f0b-8fba-abe4ba279c8a | OVN Metadata agent           | overcloud-novacompute-0.localdomain |                   | :-)   | UP    | neutron-ovn-metadata-agent |
+--------------------------------------+------------------------------+-------------------------------------+-------------------+-------+-------+----------------------------+
----

.. Then, delete the agent with XXX state:
+
[source,bash,role=execute]
----
oc exec openstackclient -- openstack network agent delete ad88316a-0f35-4a6e-87c8-db6a792e566f
oc exec openstackclient -- openstack network agent delete 3fb27b31-9381-42be-89ed-b3a6f6f6a328
oc exec openstackclient -- openstack network agent delete b182ecee-95ff-4c10-8698-23936d97b3d7
----

. Connect to the virtual machines to make sure that the process is completed successfully and had no impact on the virtual machines. Password is `gocubsgo`.
+
[source,bash,role=execute]
----
ssh cirros@172.25.250.207
----
+
Sample output:
+
----
ssh cirros@172.25.250.206
----