apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: compute-2
spec:
  tlsEnabled: false
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_VERBOSITY
      value: "2"
  services:
    - redhat
    - bootstrap
    - download-cache
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - ssh-known-hosts
    - run-os
    - reboot-os
    - ceph-client
    - install-certs
    - ovn
    - neutron-metadata
    - libvirt
    - nova
  preProvisioned: true
  networkAttachments:
    - ctlplane
  nodes:
      overcloud-novacompute-1:
        hostName: overcloud-novacompute-1.localdomain
        ansible:
          ansibleHost: 172.25.249.22
        networks:
        - name: ctlplane
          subnetName: subnet1
          defaultRoute: false
          fixedIP: 172.25.249.22
        - name: internalapi
          subnetName: subnet1
          fixedIP: 192.168.52.22
        - name: storage
          subnetName: subnet1
          fixedIP: 192.168.50.22
        - name: tenant
          subnetName: subnet1
          fixedIP: 192.168.53.22
        - name: external
          subnetName: subnet1
          fixedIP: 172.25.250.22
  nodeTemplate:
    extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        secret:
          secretName: ceph-conf-files
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    managementNetwork: ctlplane
    ansible:
      ansibleUser: tripleo-admin
      ansibleVarsFrom:
      - secretRef:
          name: subscription-manager
      - secretRef:
          name: redhat-registry
      ansibleVars:
         rhc_release: 9.2
         rhc_repositories:
             - {name: "*", state: disabled}
             - {name: "rhel-9-for-x86_64-baseos-eus-rpms", state: enabled}
             - {name: "rhel-9-for-x86_64-appstream-eus-rpms", state: enabled}
             - {name: "rhel-9-for-x86_64-highavailability-eus-rpms", state: enabled}
             - {name: "rhoso-18.0-for-rhel-9-x86_64-rpms", state: enabled}
             - {name: "fast-datapath-for-rhel-9-x86_64-rpms", state: enabled}
             - {name: "rhceph-7-tools-for-rhel-9-x86_64-rpms", state: enabled}
         edpm_network_config_template: |
           ---
           network_config:
           - type: interface
             name: eth0
             mtu: 1500
             dns_servers: {{ ctlplane_dns_nameservers }}
             domain: {{ dns_search_domains }}
             use_dhcp: false
             addresses:
             - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
           - type: interface
             name: eth1
             mtu: 1500
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ storage_ip }}/{{ storage_cidr }}
             routes: {{ storage_host_routes }}
           - type: interface
             name: eth2
             use_dhcp: true        
           - type: interface
             name: eth3
             mtu: 1500
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ internalapi_ip }}/{{ internalapi_cidr }}
             routes: {{ internalapi_host_routes }}
           - type: interface
             name: eth4
             use_dhcp: false    
           - type: interface
             name: eth5
             mtu: 1500
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ tenant_ip }}/{{ tenant_cidr }}
             routes: {{ tenant_host_routes }}
           - type: ovs_bridge
             name: br-ex
             mtu: 1500
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ external_ip }}/{{ external_cidr }}
             routes: {{ external_host_routes }}
             members:
             - type: interface
               name: eth6
               mtu: 1500
               # force the MAC address of the bridge to this interface
               primary: true
         edpm_network_config_nmstate: false
         # Control resolv.conf management by NetworkManager
         # false = disable NetworkManager resolv.conf update (default)
         # true = enable NetworkManager resolv.conf update
         edpm_bootstrap_network_resolvconf_update: false
         edpm_network_config_hide_sensitive_logs: false
         #
         # These vars are for the network config templates themselves and are
         # considered EDPM network defaults (for all computes).
         ctlplane_host_routes: []
         ctlplane_subnet_cidr: 24
         dns_search_domains: example.com
         ctlplane_mtu: 1500
         external_mtu: 1500
         external_cidr: '24'
         external_host_routes: []
         internalapi_mtu: 1500
         internalapi_cidr: '24'
         internalapi_host_routes: []
         storage_mtu: 1500
         storage_cidr: '24'
         storage_host_routes: []
         tenant_mtu: 1500
         tenant_cidr: '24'
         tenant_host_routes: []

         # EDPM network defaults
         neutron_physical_bridge_name: br-ex
         neutron_public_interface_name: eth6

         # edpm ovn-controller configuratio
         edpm_ovn_bridge: br-int
         edpm_ovn_encap_type: geneve
         ovn_monitor_all: true
         edpm_ovn_remote_probe_interval: 60000
         edpm_ovn_ofctrl_wait_before_clear: 8000
         edpm_tuned_profile: virtual-host

         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         gather_facts: false
         enable_debug: false
         
         # Do not attempt OVS major upgrades here
         edpm_ovs_packages:
         - openvswitch3.3

         edpm_bootstrap_release_version_package: []

         edpm_bootstrap_command: |
           dnf -y upgrade openstack-selinux
           rm -f /run/virtlogd.pid