apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane",
      "type": "ipvlan",
      "master": "ens9",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "172.25.249.0/24",
        "range_start": "172.25.249.30",
        "range_end": "172.25.249.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "ipvlan",
      "master": "ens6",
      "mode": "l2",
      "ipam": { 
        "type": "whereabouts", 
        "range": "192.168.52.0/24",
        "range_start": "192.168.52.30", 
        "range_end": "192.168.52.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "ipvlan",
      "master": "ens4",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.50.0/24",
        "range_start": "192.168.50.41",
        "range_end": "192.168.50.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tenant
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant",
      "type": "ipvlan",
      "master": "ens8",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.53.0/24",
        "range_start": "192.168.53.30",
        "range_end": "192.168.53.70"
      }
    }