:_mod-docs-content-type: PROCEDURE
[id="proc_retrieving-topology-specific-service-configuration_{context}"]

= Retrieving topology-specific service configuration

[role="_abstract"]
Before you migrate your databases to the {rhos_long} control plane, retrieve the topology-specific service configuration from your {rhos_prev_long} ({OpenStackShort}) environment. You need this configuration for the following reasons:

* To check your current database for inaccuracies
* To ensure that you have the data you need before the migration
* To compare your {OpenStackShort} database with the adopted {rhos_acro} database
Get the controller VIP, to use it later in the environment variable SOURCE_MARIADB_IP.

From the workstation, access to the director host and change to the stack user:
+
[source,bash,role=execute,subs=attributes]
----
ssh 172.25.250.15
sudo -i
su - stack
. stackrc
----

* In the *director host*, get the internal_api VIP from this file:
+
[source,bash,subs=attributes]
----
[student@director ~]cat /home/stack/templates/overcloud-vip-deployed.yaml

[...]
  VipPortMap:
    external:
      ip_address: 172.25.250.109
      ip_address_uri: 172.25.250.109
      ip_subnet: 172.25.250.109/24
    internal_api:
      ip_address: 192.168.52.55
      ip_address_uri: 192.168.52.55
      ip_subnet: 192.168.52.55/24
    storage:
      ip_address: 192.168.50.78
      ip_address_uri: 192.168.50.78
      ip_subnet: 192.168.50.78/24
    storage_mgmt:
      ip_address: 192.168.51.41
      ip_address_uri: 192.168.51.41
      ip_subnet: 192.168.51.41/24
[...]

[student@director ~] metalsmith list
+--------------------------------------+---------------------+--------------------------------------+-------------------------+--------+-------------------------+
| UUID                                 | Node Name           | Allocation UUID                      | Hostname                | State  | IP Addresses            |
+--------------------------------------+---------------------+--------------------------------------+-------------------------+--------+-------------------------+
| 1c708c39-91d6-4500-a395-42c081adea78 | overcloud-control0  | 3b077ad2-ddb4-462d-a573-4a3ab6aa7b84 | overcloud-controller-0  | ACTIVE | ctlplane=172.25.249.16  |
| ffca0025-c9b9-44ff-8aa1-a15d2b6f9163 | overcloud-control1  | a6416542-3e50-45c8-b824-6673722d861e | overcloud-controller-1  | ACTIVE | ctlplane=172.25.249.17  |
| 4b493c16-2dfe-4db6-985b-4aa119e98b14 | overcloud-control2  | 8d82bd92-a096-4841-8214-841a0af1f62d | overcloud-controller-2  | ACTIVE | ctlplane=172.25.249.18  |
| 91e2a13e-0b62-4181-88a3-178efd70c941 | overcloud-compute0  | 3e8426f4-e8bc-40d2-84aa-3c68ccca0dad | overcloud-novacompute-0 | ACTIVE | ctlplane=172.25.249.19  |
| ed1f3a65-e80f-458b-9c2d-873e9073e3bb | overcloud-compute1  | 1f6c4f74-f7cd-4c4f-bd41-89083d441d9d | overcloud-novacompute-1 | ACTIVE | ctlplane=172.25.249.22  |
| 51d45604-8bf8-43f9-9718-d704398296e3 | overcloud-networker | b5f71cd8-5f42-46a8-8c51-a75608745744 | overcloud-networker     | ACTIVE | ctlplane=172.25.249.250 |
+--------------------------------------+---------------------+--------------------------------------+-------------------------+--------+-------------------------+

[student@director ~] ssh tripleo-admin@172.25.249.16
[tripleo-admin@overcloud-controller-0 ~]$ 
sudo grep -rI 'listen mysql' -A10 /var/lib/config-data/puppet-generated/ | grep bind
/var/lib/config-data/puppet-generated/haproxy/etc/haproxy/haproxy.cfg-  bind 192.168.52.55:3306 transparent

[tripleo-admin@overcloud-controller-0 ~]$ logout


----
+
SOURCE_MARIADB_IP is then 192.168.52.55
CONTROLLER1_IP is then 172.25.249.16
+
In the *director host*, copy the overcloud-passwords from the director node to the student user home directory:
+
[source,bash,role=execute,subs=attributes]
----
sudo cp /home/stack/overcloud-deploy/overcloud/overcloud-passwords.yaml /home/student/overcloud-passwords.yaml
sudo chown student:student /home/student/overcloud-passwords.yaml
sudo cp /home/stack/.ssh/id_rsa_tripleo* /home/student/.ssh/
sudo chown student:student /home/student/.ssh/id_rsa_tripleo
sudo chown student:student /home/student/.ssh/id_rsa_tripleo.pub
----
+
In the *workstation host*, copy the overcloud-passwords from the director node to the utiliy node:
+
[source,bash,role=execute,subs=attributes]
----
scp student@172.25.250.15:~/overcloud-passwords.yaml lab@utility:~/overcloud-passwords.yaml
scp student@172.25.250.15:~/.ssh/id_rsa_tripleo* lab@utility:~/.ssh/
scp ~/.ssh/lab_rsa* lab@utility:~/.ssh/
----
+
In the *utility host* log in to the Red Hat registry and create the secret:
+
[source,bash,role=execute,subs=attributes]
----
oc get secret/pull-secret -n openshift-config -o json | jq -r '.data.".dockerconfigjson"' | base64 -d > authfile
podman login registry.redhat.io --authfile authfile
oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=authfile

----
+
.Prerequisites

. In the *utility host*, define the following shell variables. Replace the example values with values that are correct for your environment:
+
----
PASSWORD_FILE="$HOME/overcloud-passwords.yaml"
MARIADB_IMAGE=registry.redhat.io/rhoso/openstack-mariadb-rhel9:18.0
declare -A TRIPLEO_PASSWORDS
CELLS="default"
for CELL in $(echo $CELLS); do
  TRIPLEO_PASSWORDS[$CELL]="$PASSWORD_FILE"
done
declare -A SOURCE_DB_ROOT_PASSWORD
for CELL in $(echo $CELLS); do
  SOURCE_DB_ROOT_PASSWORD[$CELL]=$(cat ${TRIPLEO_PASSWORDS[$CELL]} | grep ' MysqlRootPassword:' | awk -F ': ' '{ print $2; }')
done
----
+

. Define the following shell variables. Replace the example values with values that are correct for your environment:
+
----
MARIADB_CLIENT_ANNOTATIONS='--annotations=k8s.v1.cni.cncf.io/networks=internalapi'
MARIADB_RUN_OVERRIDES="$MARIADB_CLIENT_ANNOTATIONS"
CONTROLLER1_SSH="ssh -i /home/lab/.ssh/id_rsa_tripleo tripleo-admin@172.25.249.16"

declare -A SOURCE_MARIADB_IP
SOURCE_MARIADB_IP[default]=192.168.52.55
----

[NOTE]
The source cloud always uses the same password for cells databases. For that reason, the same passwords file is used for all cells stacks. However, split-stack topology allows using different passwords files for each stack.

.Procedure

. Export the shell variables for the following outputs and test the connection to the {OpenStackShort} database:
+
----
unset PULL_OPENSTACK_CONFIGURATION_DATABASES
declare -xA PULL_OPENSTACK_CONFIGURATION_DATABASES
for CELL in $(echo $CELLS); do
  PULL_OPENSTACK_CONFIGURATION_DATABASES[$CELL]=$(oc run mariadb-client-1-$CELL ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
    mysql -rsh "${SOURCE_MARIADB_IP[$CELL]}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD[$CELL]}" -e 'SHOW databases;')
done
----
+
If the connection is successful, the expected output is nothing.
+
[NOTE]
The `nova`, `nova_api`, and `nova_cell0` databases are included in the same database host for the main overcloud {orchestration_first_ref} stack.
ifeval::["{build_variant}" != "ospdo"]
Additional cells use the `nova` database of their local Galera clusters.
endif::[]

. Run `mysqlcheck` on the {OpenStackShort} database to check for inaccuracies:
+
----
unset PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK
declare -xA PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK
run_mysqlcheck() {
  PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK=$(oc run mariadb-client-2-$1 ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
    mysqlcheck --all-databases -h ${SOURCE_MARIADB_IP[$CELL]} -u root -p"${SOURCE_DB_ROOT_PASSWORD[$CELL]}" | grep -v OK)
}
for CELL in $(echo $CELLS); do
  run_mysqlcheck $CELL
done
if [ "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK" != "" ]; then
  for CELL in $(echo $CELLS); do
    MYSQL_UPGRADE=$(oc run mariadb-client-3 ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
      mysql_upgrade -v -h ${SOURCE_MARIADB_IP[$CELL]} -u root -p"${SOURCE_DB_ROOT_PASSWORD[$CELL]}")
    # rerun mysqlcheck to check if problem is resolved
    run_mysqlcheck
  done
fi
----

. Get the {compute_service_first_ref} cell mappings:
+
----
export PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS=$(oc run mariadb-client-1 ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
    mysql -rsh "${SOURCE_MARIADB_IP['default']}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD['default']}" nova_api -e \
    'select uuid,name,transport_url,database_connection,disabled from cell_mappings;')
----

. Get the hostnames of the registered Compute services:
+
----
unset PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES
declare -xA PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES
for CELL in $(echo $CELLS); do
  PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES[$CELL]=$(oc run mariadb-client-4-$CELL ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
    mysql -rsh "${SOURCE_MARIADB_IP[$CELL]}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD[$CELL]}" -e \
      "select host from nova.services where services.binary='nova-compute' and deleted=0;")
done
----

. Get the list of the mapped {compute_service} cells:
+
----
export PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS=$($CONTROLLER1_SSH sudo podman exec -it nova_conductor nova-manage cell_v2 list_cells)
----

. Store the exported variables for future use:
+
----
unset SRIOV_AGENTS
declare -xA SRIOV_AGENTS <1>
for CELL in $(echo $CELLS); do
  RCELL=$CELL
  [ "$CELL" = "$DEFAULT_CELL_NAME" ] && RCELL=default
  cat > ~/.source_cloud_exported_variables_$CELL << EOF
unset PULL_OPENSTACK_CONFIGURATION_DATABASES
unset PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK
unset PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES
declare -xA PULL_OPENSTACK_CONFIGURATION_DATABASES
declare -xA PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK
declare -xA PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES
PULL_OPENSTACK_CONFIGURATION_DATABASES[$CELL]="$(oc run mariadb-client-5-$CELL ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
  mysql -rsh ${SOURCE_MARIADB_IP[$RCELL]} -uroot -p${SOURCE_DB_ROOT_PASSWORD[$RCELL]} -e 'SHOW databases;')"
PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK[$CELL]="$(oc run mariadb-client-6-$CELL ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
  mysqlcheck --all-databases -h ${SOURCE_MARIADB_IP[$RCELL]} -u root -p${SOURCE_DB_ROOT_PASSWORD[$RCELL]} | grep -v OK)"
PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES[$CELL]="$(oc run mariadb-client-7-$CELL ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
  mysql -rsh ${SOURCE_MARIADB_IP[$RCELL]} -uroot -p${SOURCE_DB_ROOT_PASSWORD[$RCELL]} -e \
  "select host from nova.services where services.binary='nova-compute' and deleted=0;")"
if [ "$RCELL" = "default" ]; then
  PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS="$(oc run mariadb-client-2 ${MARIADB_RUN_OVERRIDES} -q --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
    mysql -rsh ${SOURCE_MARIADB_IP[$RCELL]} -uroot -p${SOURCE_DB_ROOT_PASSWORD[$RCELL]} nova_api -e \
      'select uuid,name,transport_url,database_connection,disabled from cell_mappings;')"
  PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS="$($CONTROLLER1_SSH sudo podman exec -it nova_conductor nova-manage cell_v2 list_cells)"
fi
EOF
done
chmod 0600 ~/.source_cloud_exported_variables*
----
+
<1> If `neutron-sriov-nic-agent` agents are running in your {OpenStackShort} deployment, get the configuration to use for the data plane adoption.

.Next steps

This configuration and the exported values are required later, during the data plane adoption post-checks. After the {OpenStackShort} control plane services are shut down, if any of the exported values are lost, re-running the `export` command fails because the control plane services are no longer running on the source cloud, and the data cannot be retrieved. To avoid data loss, preserve the exported values in an environment file before shutting down the control plane services.
