:_mod-docs-content-type: PROCEDURE
[id="adopting-the-compute-service_{context}"]

= Adopting the {compute_service}

[role="_abstract"]
To adopt the {compute_service_first_ref}, you patch an existing `OpenStackControlPlane` custom resource (CR) where the {compute_service} is disabled. The patch starts the service with the configuration parameters that are provided by the {rhos_prev_long} ({OpenStackShort}) environment. The following procedure describes a single-cell setup.

//[NOTE]
//The following example scenario describes a single-cell setup. Real
//multi-stack topology that is recommended for production use results in cells having a different database layout, and should use different naming schemes. kgilliga: We might reinstate this note after multi-cell is finished in Feature Release 1.

.Prerequisites

* You have completed the previous adoption steps.
* You have defined the following shell variables. Replace the following example values with the values that are correct for your environment:
+
[source,bash,role=execute]
----
alias openstack="oc exec -t openstackclient -- openstack"

DEFAULT_CELL_NAME="cell3"
RENAMED_CELLS="cell1 cell2 $DEFAULT_CELL_NAME"
----
+
** The source cloud `default` cell takes a new `$DEFAULT_CELL_NAME`. In a multi-cell adoption scenario, the 'default' cell might retain its original name,`DEFAULT_CELL_NAME=default`, or become renamed as a cell that is free for use. Do not use other existing cell names for `DEFAULT_CELL_NAME`, except for `default`.
** If you deployed the source cloud with a `default` cell, and want to rename it during adoption, define the new name that you want to use, as shown in the following example:
+
[source,bash,role=execute]
----
DEFAULT_CELL_NAME="cell1"
RENAMED_CELLS="cell1"
----

.Procedure

. Patch the `OpenStackControlPlane` CR to deploy the {compute_service}:
+
[NOTE]
This procedure assumes that {compute_service} metadata is deployed on the top level and not on each cell level. If the {OpenStackShort} deployment has a per-cell metadata deployment, adjust the following patch as needed. You cannot run the metadata service in `cell0`.
To enable the metadata services of a local cell, set the `enabled` property in the `metadataServiceTemplate` field of the local cell to `true` in the `OpenStackControlPlane` CR.
+
[source,bash,role=execute]
----
rm -f celltemplates
for CELL in $(echo $RENAMED_CELLS); do
 cat >> celltemplates << EOF
        ${CELL}:
          hasAPIAccess: true
          cellDatabaseAccount: nova-$CELL
          cellDatabaseInstance: openstack-$CELL
          cellMessageBusInstance: rabbitmq-$CELL
          metadataServiceTemplate:
            enabled: false
            override:
                service:
                  metadata:
                    annotations:
                      metallb.universe.tf/address-pool: internalapi
                      metallb.universe.tf/allow-shared-ip: internalapi
                      metallb.universe.tf/loadBalancerIPs: 192.168.52.$(( 88 + ${CELL##*cell} ))
                  spec:
                    type: LoadBalancer
            customServiceConfig: |
              [workarounds]
              disable_compute_service_check_for_ffu=true
          conductorServiceTemplate:
            customServiceConfig: |
              [workarounds]
              disable_compute_service_check_for_ffu=true
EOF
done

cat > oscp-patch.yaml << EOF
spec:
  nova:
    enabled: true
    apiOverride:
      route: {}
    template:
      secret: osp-secret
      apiDatabaseAccount: nova-api
      apiServiceTemplate:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 192.168.52.89
              spec:
                type: LoadBalancer
        customServiceConfig: |
          [workarounds]
          disable_compute_service_check_for_ffu=true
      metadataServiceTemplate:
        enabled: true
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 192.168.52.89
            spec:
              type: LoadBalancer
        customServiceConfig: |
          [workarounds]
          disable_compute_service_check_for_ffu=true
      schedulerServiceTemplate:
        customServiceConfig: |
          [workarounds]
          disable_compute_service_check_for_ffu=true
      cellTemplates:
        cell0:
          hasAPIAccess: true
          cellDatabaseAccount: nova-cell0
          cellDatabaseInstance: openstack
          cellMessageBusInstance: rabbitmq
          conductorServiceTemplate:
            customServiceConfig: |
              [workarounds]
              disable_compute_service_check_for_ffu=true
EOF
cat celltemplates >> oscp-patch.yaml
oc patch openstackcontrolplane openstack  --type=merge --patch-file=oscp-patch.yaml
----

[NOTE]
The local Conductor services are started for each cell, while the superconductor runs in `cell0`.
Note that `disable_compute_service_check_for_ffu` is mandatory for all imported Compute services until the external data plane is imported, and until the Compute services are fast-forward upgraded. For more information, see xref:adopting-compute-services-to-the-data-plane_data-plane[Adopting Compute services to the {rhos_acro} data plane] and xref:performing-a-fast-forward-upgrade-on-compute-services_data-plane[Upgrading Compute services].

. Wait for Nova control plane services' CRs to become ready:
+
[source,bash,role=execute,subs=attributes]
----
oc wait --for condition=Ready --timeout=300s Nova/nova
----

.Verification

* Check that {compute_service} endpoints are defined and pointing to the
control plane FQDNs, and that the Nova API responds:
+
[source,bash,role=execute]
----
openstack endpoint list | grep nova
openstack server list
----
+
Sample output:
----
| 764454a0fe6540829496a91706be0fc9 | regionOne | nova         | compute      | True    | internal  | http://nova-internal.openstack.svc:8774/v2.1                 |
| ce98dcc7e5a54ae4b08274ecf36c1a91 | regionOne | nova         | compute      | True    | public    | http://nova-public-openstack.apps.ocp4.example.com/v2.1      |
+--------------------------------------+--------------------+--------+-----------------------------------------+--------+--------+
| ID                                   | Name               | Status | Networks                                | Image  | Flavor |
+--------------------------------------+--------------------+--------+-----------------------------------------+--------+--------+
| 32316d67-70bc-4c39-a462-93d18a3f6594 | server-2-compute-1 | ACTIVE | private=172.25.250.207, 192.168.100.91  | cirros | tiny   |
| e776a713-6f7c-419a-a153-89fd1abb5a2d | server-1-compute-0 | ACTIVE | private=172.25.250.206, 192.168.100.187 | cirros | tiny   |
+--------------------------------------+--------------------+--------+-----------------------------------------+--------+--------+
----

[NOTE]
====
At this point, the {compute_service} control plane services do not control the existing {compute_service} workloads. The control plane manages the data plane only after the data adoption process is completed. For more information, see xref:adopting-compute-services-to-the-data-plane_data-plane[Adopting Compute services to the {rhos_acro} data plane].
====

[IMPORTANT]
To import external Compute services to the {rhos_acro} data plane, you must upgrade them first.
For more information, see xref:adopting-compute-services-to-the-data-plane_data-plane[Adopting Compute services to the {rhos_acro} data plane], and xref:performing-a-fast-forward-upgrade-on-compute-services_data-plane[Performing a fast-forward upgrade on Compute services].
